# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:20
from __future__ import unicode_literals

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='pic',
            field=models.ImageField(upload_to=about.models.user_directory_path),
        ),
    ]
