# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('logo', models.ImageField(upload_to=games.models.user_directory_path)),
                ('platform', models.CharField(max_length=140)),
                ('releasedate', models.CharField(max_length=140)),
                ('description', models.TextField()),
            ],
        ),
    ]
